### ISSUE TITLE
Get `standardise_dates()` to properly work date ranges, incomplete dates and ambiguous date formats

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#102]
The functionality is built into the function but it is not currently being deployed properly.

**Comment by EstherPeev** [comment]
Some date formats such as "0000-00-00" failed to pass in qEnviron. It is creating an NA automatically and the function runs with a warning message. This can be addressed in the next release of qData.

**Comment by jhollway** [comment]
But shouldn't "0000-00-00" become an NA?

**Comment by EstherPeev** [comment]
It is creating a warning message so I think we can add this format in standardise_dates() to avoid the warning message to appear.

**Comment by jhollway** [comment]
Try adding `suppressWarnings()` to that line of code in qData

**Comment by EstherPeev** [comment]
CIESIN database in qEnviron has dates under YYYY format, which should be treated as range dates. CIESIN can be exported into the agreements database only when `standardise_dates()` is updated and will be able to treat range dates.

**Comment by henriquesposito** [comment]
@EstherPeev I see, I will work on a fix that allows you to move forward with the dataset. Thank you for the message.

**Comment by henriquesposito** [comment]
This issue has been solved with the later version of `standardise_dates()` that returns character observations to be later resolved using the resolve family of functions into dates.
