### ISSUE TITLE
Report_data() does not iterate over databases when multiple ones are present in a given package

### ISSUE THREAD

**Issue by BBieri** [globalgov/qData#105]
Report_data() does not iterate over databases when multiple ones are present in a given package. Since there will be multiple databases in each package, we should iterate over all databases in a package to give the user an overview of its content.

**Comment by BBieri** [comment]
Plus a find a nicer display format for dates to be displayed as dates and not characters (i.e. replace rbind and create a dataframe or find another way of binding these metadata elements).

**Comment by jhollway** [comment]
see `vcdExtra::datasets("qStates")` for an example
