### ISSUE TITLE
Make `setup_package ()` function accept more than two names and more than two authors

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#106]
For now the function accepts only 2 names for up to 2 authors, this should be improved.  Roles of authors should also be better distinguished by the `setup_package()` function, as roles can be separate and developers can have one or many roles in the package.

**Comment by jhollway** [comment]
Relate to #90 ?

**Comment by jhollway** [comment]
Might be neat to offer the option to add authors by [ORCID](https://orcid.org/) lookup or similar

**Comment by BBieri** [comment]
Just pushed my first attempt at reworking the `setup_package()` function. I added the same scraping tool that I used for the `add_authors()` function hence the function now primarily takes a vector of ORCID numbers as input while still allowing for an alternative manual entry of now up to five authors. If more than five authors are mentioned, the user is redirected to the `add_author()` function instead and invited to put a maximum of 5 authors as inputs. 

I realize that this may seem more of a workaround than a solution but editing templates recursively is quite challenging. Would love your feedback on that @henriquesposito, @jhollway, @EstherPeev.

**Comment by henriquesposito** [comment]
@BBieri I just went through your code and I like the solution you implemented. It is a smart way to work with what is already there while adding some new functionality. 

However, I have been testing the function and ran into a few issues:

- names are not being pasted into description file for one author
- entering my Orcid name also does not paste the names properly in the description file

I have been looking into the issue to see what is happening.
