### ISSUE TITLE
`get_packages` does not work according to vignette

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#117]
The function appears to requires that the name of the organization as well as the name of the package are entered to work properly. This is not how the vignette or examples demonstrate.

**Comment by henriquesposito** [comment]
Related to this issue, xfun is relied upon for the function to work. However, currently it is a suggested package and not a dependency which can sometimes cause an issue for users.

**Comment by henriquesposito** [comment]
The function was updated to assume that if no user is declared before package name, package is in globalgov. 

The comment above has been moved to a more appropriate issue (#96).

**Comment by jhollway** [comment]
Good idea, especially for now!
