### ISSUE TITLE
Update `setup_package()` so that it sets up a license.md document in new q package

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#119]
With the issues with license we had on `setup_package()` and the modifications made, we forgot to make sure a license.md document is setup for documentation purposes. This should be added as one of the templates copied to new package when using the function.

**Comment by henriquesposito** [comment]
@EstherPeev qEnviron currently does not have a license.md file which makes so that the license documentation is not rendered. Could you please add the file to the package?

**Comment by EstherPeev** [comment]
@henriquesposito Yes, I have just added it.

**Comment by henriquesposito** [comment]
@EstherPeev Thank you!

The template license has also been setup for qData so that when the `setup_package()` function is run, the LICENSE.md file is also added to the new q package.
