### ISSUE TITLE
Warning messages with pkgdown site

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#128]
Sometimes warning messages are displayed for some command lines on pkgdown sites build for qPackages. Please find out whether there is a way to make so that these warning messages are not displayed.

**Comment by henriquesposito** [comment]
The only warning left in pkgdown website relates using `{lubridate}` and `{anytime}` in the `standardise_dates()` and they are actually helpful to show how our function performs better. Most of the warnings were addressed in the last PR as they originated from little bugs here and there.

**Comment by jhollway** [comment]
Ok, can we suppress these (expected) warnings somehow?

**Comment by henriquesposito** [comment]
Yes, we can. However, I think it would show in the code if we use the `suppressWarnings()` function in the examples. Is that acceptable? If that is not an issue, I can update that now. Other than that, I cannot think of another way of doing so.

**Comment by jhollway** [comment]
Where is the warning a problem? In R CMD check or on the webpage/documentation?

**Comment by henriquesposito** [comment]
The warnings are not an issue at all for the R CMD check. 

The issue pointed is that they display on the pkgdown website and do not look "great".

**Comment by jhollway** [comment]
Then wrap the function that is complaining (`lubridate::as_date()`?) in `suppressWarnings()` so that users can see where issues might arise.

**Comment by henriquesposito** [comment]
Done. Thank you.
