### ISSUE TITLE
Create Zenodo DOI for package

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#149]
See https://ropensci.org/blog/2021/02/16/package-citation/ for more

**Comment by henriquesposito** [comment]
I have created a citation file for all the packages in globalgov. However, I do not have the authorizations to turn on Zenodo for the repository to create a DOI. @jhollway could you allow Zenodo to connect with the repositories in globalgov? 

Once you do so we can add a badge on the readme file for the next release and a DOI section in the citation files.

**Comment by henriquesposito** [comment]
From what I understand, Zenodo requires that we [create a release for the packages for the DOI number be activated](https://guides.lib.berkeley.edu/citeyourcode). Alternatively, it is possible that it will automatically create a DOI for the next release we have.

@jhollway Would you like to create a release for the packages or wait for our next release to activate the DOI?

Once the DOI is available, we can then can add a badge and a section to the citation files.
