### ISSUE TITLE
Re-think print argument for report_data family of functions

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#160]
An alternative to the solution of using print as an argument is to instead create an object or list of the elements that would then get assigned, or, if no assigned, then it would print. See also summary() etc.

This can be addressed once we add the data_evolution() function (issue #134).

**Comment by BBieri** [comment]
Good idea, I can define a new class for the object that the family returns as well as a specific print method for it. See [this](https://stackoverflow.com/questions/13056392/print-if-not-assigned) for the general idea.

**Comment by BBieri** [comment]
Mainly solved. The only remaining issue is that when the new print function for the custom "qReport" class is not loaded in the environment, the function prints the object's class attribute after the print console output. Would love your input on that @henriquesposito.

**Comment by henriquesposito** [comment]
Great @BBieri ! Yes, the print of the object's class attribute is a bit annoying and we should try to get rid off it, but other than that really good job! I will also have a play around with the function to try and not print the class. Thank you.

**Comment by henriquesposito** [comment]
@BBieri The documentation for class (?class) reads:

"When a generic function fun is applied to an object with class attribute c("first", "second"), the system searches for a function called fun.first and, if it finds it, applies it to the object. If no such function is found, a function called fun.second is tried. If no class name produces a suitable function, the function fun.default is used (if it exists). If there is no class attribute, the implicit class is tried, then the default method."

So I assume that if we set a helper function called fun.qreport() outside of data_contrast(), just as below, it should work.

fun.qReport<- function(qReport) {
  print(qReport[1:length(qReport)])
}

I just tried on my system and it appears to work. Is that a possible solution?

**Comment by BBieri** [comment]
Indeed, the print method for qReport should be defined outside of the report function, my mistake. However, I still get the attribute of the object with your version :/

Thanks a lot for taking a look at it!

**Comment by henriquesposito** [comment]
You are right Bernhard, it was not a fix. However, setting up the class to a list with "listof" does! I have just pushed these changes and hopefully this issue can be moved to awaiting deployment now.

**Comment by BBieri** [comment]
Great @henriquesposito! Thanks again for looking into it :)
