### ISSUE TITLE
Create developer vignette: Contributing a qData package

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#67]

**Comment by henriquesposito** [comment]
I have uploaded the first version of the vignette to the develop branch.

**Comment by henriquesposito** [comment]
As of now we have only the `setup_package()` function on this vignette. However, users may want to use qDatr to wrangle data and not necessarily to setup a new package. Should we create a package specific vignette and add the `setup_package()` function there? Then, the get started with qDatr vignette becomes a short and more broad overview of the package, what can be used for and perhaps how to install it.

**Comment by jhollway** [comment]
@henriquesposito please reassemble all the developer-side steps and functions into a single, informative vignette.

**Comment by jhollway** [comment]
Please don't forget to cover "standardising your data" as a section here.
