### ISSUE TITLE
Update ambig_data() so that it converts (extreme) future dates to a consistent date

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#70]
The tests for this feature were set up but have been skipped for the ambig_data() function in relation to converting extreme future dates. Make sure the function coverts extreme future dates to 9999-12-3.

**Comment by henriquesposito** [comment]
@jhollway I am having issues trying to solve this issue. Could you please point me in the right direction here? I have tried solving in a varied of ways, but I cannot get it to convert future dates.

**Comment by jhollway** [comment]
Try something like checking for a date being more than 100 years from the `Sys.Date()` and if so return "9999-12-31" instead.

**Comment by henriquesposito** [comment]
I tried to modify the `standardise_date()` function to convert the future dates. However, I have not been successful. Every time I modified the function, more tests it would fail. 

Then, I went back to the `recent()` function we have to reset unlike centuries of data and transform data formats. As I see it, this is a complementary function to `standardise_date()` to be used beforehand depending on the format of dates (6 digits as opposed to 8 digits for example). There I tried to adapt the function to solve the issue and, although I was able to pass the specific test on future dates, other tests began to fail due to the alterations in the function. 

Finally, I attempted to create a function similar to `recent()` that would do this on its' own (as an attempt to isolate the issue and try to insert the solution within a function later on). I solved the issue but now I cannot get the function to let past dates intact. I know this is not even close to what we are looking for, but I am having issues with this task (perhaps I am overthinking a lot here but nonetheless). I have tried to deal with this issue for a few hours on Friday and all day today.

```
future <- function(dates, sep = NULL){

  if(is.null(sep)) sep <- substr(gsub("\\d","",dates),1,1)[1]
  if(sep==".") sep <- "\\."
  # threshold
  thresh <- as.numeric(substr(Sys.Date(),1,4))
  # year
  x <- matrix(as.numeric(unlist(strsplit(dates, sep))), ncol=3, byrow = T)
  ypos <- which(apply(x, 2, function(y) any(nchar(y)==4)))
  dpos <- setdiff(which(apply(x, 2, function(y) any(y>12) & all(y<32))), ypos)
  mpos <- setdiff(setdiff(1:3, ypos), dpos)

  #convert
  if(nrow(x)==1){
    y <- ifelse(as.numeric(x[ypos]) > (thresh),
                formatC("9999", width = 4, flag = "0"), 
                formatC(x[ypos], width = 4, flag = "0"))
    if(as.numeric(x[ypos]) <= (thresh)) m <- formatC(x[mpos], width = 2, flag = "0") else(m <- "12")
    if(as.numeric(x[ypos]) <= (thresh)) d <- formatC(x[dpos], width = 2, flag = "0") else(d <- "31")
    out <- paste(y,m,d,sep = "-")
  }
  out
}
```

I would like to be able to at least try and solve this on my own for a bit longer (now it is a question of honor and sunk costs fallacious thinking haha), so @jhollway could you please just help me a bit more here? 

To be clear, I do think we should deal with the conversion of future dates in the `standardise_date()`  function and not add another function to do this, I just need some help to get there I think.

**Comment by jhollway** [comment]
@henriquesposito it was easier just to solve it, but if you need any explanation of what is happening here, I'm happy to provide it. Indeed, it's easy to overthink these problems. Good point about `recent()` though, we might try to reintegrate parts of it into `standardise_dates()` so that users can just use a single call.
