### ISSUE TITLE
Update standardise_dates() so that it converts past historical dates correctly

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#73]
Update `standardise_dates()` so that it converts historical dates and other date formats that have 6 instead of 8 digits.  This can be done by incorporating some of the `recent()` function features so that all the conversion of dates can be done with one function.

**Comment by henriquesposito** [comment]
Some of the `recent()` functionality has been added. 

Now I run into issues converting past historical dates that start with a 0 (or that have a 0 added to the years), have a minus sign in front, or contain BC or AC.  It appears that anytime::anydate() has issues with years that start with 0 or a minus (it returns NA). And, even if I use lubridate, anytime still has to "work" on the dates in the function. Do you have any idea how to fix this? 

If we change the function to work with completely with lubridate, years that start with 0 are accepted the minus sign for negative years are removed. 

@jhollway I might need some help working on this issue.

**Comment by jhollway** [comment]
I think you need to think about the ordering of these operations, and maybe use if() or ifelse() statements to avoid triggering errors.

I don't think either `{lubridate}` or `{anytime}` do particularly well with very historical dates. You may need to reformulate this as a character string first.

**Comment by henriquesposito** [comment]
I was a bit stuck with this issue, apologies it is taking so long. 

The problem I was facing here has to do with the fact that I cannot find a way to deal with negative dates in R. While I can transform the historical date values into what we want as output, by treating them as characters and keeping the negative sign, once you transform them into a date form the negative sign is either dropped (and the dates become positive) or the dates appear as NA. Though if we leave them how we want but as character, operations with dates become an issue. 

After much looking, I found this issue: https://github.com/tidyverse/lubridate/issues/2 . This means the best way around is to compose a helper function for dealing with these dates that subtracts from value giving a negative date that is still in posixCT format. Luckily, someone else has done it already for reference here: https://github.com/RMHoek/NOAAearthquakeAnalysis/blob/master/R/as_BC_date.R .  

I will set up a helper similar function and think with a bit more work I now can address the issue.

**Comment by henriquesposito** [comment]
I am making good progress here and already submit some changes. The function now handles year dates for years that begin with a 0 as well as dates for which the year only contains 3 digits. 

I have started also to deal with AD and BC (negative) dates, though I run into an issue when detecting or trying to remove these patterns in the strings.  The issue being that {stringr} does not appear to be detecting the patterns in the first place. 

```
# The code to remove the AD and to treat the date as if it were a positive date value as I have is:
dates <- stringr::str_remove_all(dates, "^(ad|AD|Ad|aD)$")  
```

I have tried several versions of the code above, though the issue remains the recognition of the pattern, which is also essential to dealing with negative dates signaled by BC. I have a the impression that I am missing something simple with the syntax but have not yet found much on this online ...

@jhollway Do you have any idea of what I am missing? Thank you.

**Comment by Tayflo** [comment]
Hello there. @henriquesposito maybe your problem is dealing correctly with regexes (regular expressions)?

If I may point out, `^` and `$` are used to indicate beginning/end of a string vector.

A bit of code says better than a long speech:
```r
dates_input <- c("ad", "15 AD", "1999 ad ", "19 ad 14")

# Strict begin/end
stringr::str_remove_all(dates_input, "^(ad|AD|Ad|aD)$")
#> [1] ""         "15 AD"    "1999 ad " "19 ad 14"

# Strict end
stringr::str_remove_all(dates_input, "(ad|AD|Ad|aD)$")
#> [1] ""         "15 "      "1999 ad " "19 ad 14"

# Anywhere
stringr::str_remove_all(dates_input, "(ad|AD|Ad|aD)")
#> [1] ""       "15 "    "1999  " "19  14"

# (?i) flag for case-insentivity in stringr is shorter
stringr::str_remove_all(dates_input, "(?i)ad")
#> [1] ""       "15 "    "1999  " "19  14"
```
<sup>Created on 2021-01-21 by the [reprex (!=regex) package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is for the sake of the example, you should probably `stringr::str_trim()` your data also.

Some resources about regular expressions, and regular expressions in R:
- https://regexr.com/
- https://raw.githubusercontent.com/rstudio/cheatsheets/master/strings.pdf
- https://adamspannbauer.github.io/2018/01/16/r-regex-tester-shiny-app/
- http://www.goring.org/resources/tutorial.html

Hope it helps :-)

**Comment by henriquesposito** [comment]
Hello @Tayflo, thank you for your help. 

I had indeed tried many of these regexes before and kept running into issues. 

Though you did provide me with the solution, trimming white spaces! The issue was not removing the AD strings, rather that by doing so white spaces were left that caused the function not to run properly. 

Thank you also for the tips about GitHub. And hope you stay tuned on all of our packages under development.
