### ISSUE TITLE
Update export_data() function description in the vignette

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qData#81]
The vignette contains the old export_data() documentation. Need to update it to the new version of the export_data() function, that creates a new list of dataframes instead of separate dataframes.

**Comment by EstherPeev** [comment]
@jhollway 

We looked into the data_export() function with Bernhard and make few changes in the description to include the database name as a string and to provide more information in the "connecting data" section. I did the changes in the develop branch which does not make the changes appear until a pull request. Should I make a pull request to make the changes on the main branch?

**Comment by jhollway** [comment]
Great, thank you @EstherPeev . You can open a new PR if you like, but we may try and accumulate a few additional changes before merging.

**Comment by EstherPeev** [comment]
@jhollway 

I just did the pull request as I thought it could be useful for me to understand how to do it.
