### ISSUE TITLE
Create open graph image

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#84]
https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

**Comment by jhollway** [comment]
Under https://github.com/globalgov/qData/settings > Options > Social preview

**Comment by BBieri** [comment]
## Update 25.01.2021 
- Created new package logos _(need to be slightly tweaked)_
- Created openGraph banner
- **All design material will from now on be located in the Design Resources repo.**

**Comment by jhollway** [comment]
Do you propose we link to this other repo then when e.g. building repos, or copy across the latest version to the individual packages as/when necessary?

**Comment by BBieri** [comment]
Actually, we could create a public repo with design resources (vector files) where we have a document outlining the design guidelines of the whole project and invite external contributors to contribute their own logo designs when they create packages. 

In addition, I would also create a private one for internal contributors that houses the design files that can be modified and other miscellaneous elements. 

What do you think?

**Comment by jhollway** [comment]
Let's keep a private repo as an internal design warehouse, and replace `man/figures/logo.png` as necessary. This should ensure everything (incl. pkgdown) works correctly.
