### ISSUE TITLE
`setup_package()` function is not allowing second author as input

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qData#89]

**Comment by jhollway** [comment]
Yes, this needs to be fixed. @henriquesposito perhaps we can also set it up so that the function includes two different arguments?:

- `authors = ` which would take a character vector of author names (or ORCID accounts?) for the initial package setup
- `new_author = ` which would allow package contributors to append a new author name

**Comment by jhollway** [comment]
We could also think about adding and distinguishing between package and dataset contributors as [special roles](https://www.loc.gov/marc/relators/relaterm.html) in [the description](https://r-pkgs.org/description.html#author).

**Comment by henriquesposito** [comment]
Good catch @EstherPeev ! I will take a look at this and try to help in fixing the bug and improving the function. 

When running the `setup_package()` function I also noticed the folder structure in the package was missing the R folder, I added a missing code line that should take care of the issue and setup the folder properly when running the function.

**Comment by henriquesposito** [comment]
There is also a 'name' argument missing error that the function is now returning. The error is related to the `usethis::use_ccby_license()' line in the function. It can be solved in different ways (1) by commenting out the line or (2) specifying the name parameter or (3) by inserting the license text template into the package. As of now, the name argument has been set to "packageAuthor" and issue is temporarily resolved.

**Comment by EstherPeev** [comment]
I added "dtc" as a type of contributor in the description templates which stands for "data contributor" according this [webpage] (https://www.loc.gov/marc/relators/relaterm.html).
